---
steps:
  - label: build
    agents:
      queue: link-aws-peers-sjc
    artifact_paths:
      - "artifact"
    command: buildkite-agent meta-data set foo bar
  - command:
    - YES=$(buildkite-agent meta-data get --job 6424b441-e0a8-4fdd-b13a-f72dddb15353 notify)
    - NO=$(buildkite-agent meta-data get --job 962cbd4a-bfe7-4b98-be59-32c9c0824752 notify)
    - echo $YES
    - echo $NO
  # This straight up fuckin fails if the metadata aint set. 



  # For THIS BUILD, was notify metadata set?
  # If so, buildkite-agent meta-data --job ${NOTIFY} set package-${BUILDKITE_ORGANIZATION_SLUG} ${BUILDKITE_MESSAGE}
  # In the final project, we use the actual S3 url instead of buildkite message, and we use DEVICE_VARIANT instead of orgslug
